(custom-set-faces
 '(default ((t (:stipple nil :background "gray25" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height unspecified :width normal :family unspecified))))
 '(border ((t (:background "#102e4e"))))
 '(change-log-acknowledgement-face ((t (:italic t :slant italic :foreground "CadetBlue"))))
 '(change-log-conditionals-face ((t (:foreground "SeaGreen2"))))
 '(change-log-date-face ((t (:foreground "burlywood"))))
 '(change-log-email-face ((t (:foreground "SeaGreen2"))))
 '(change-log-file-face ((t (:bold t :weight bold :foreground "goldenrod"))))
 '(change-log-function-face ((t (:foreground "SeaGreen2"))))
 '(change-log-list-face ((t (:bold t :weight bold :foreground "DeepSkyBlue1"))))
 '(change-log-name-face ((t (:foreground "gold"))))
 '(cursor ((t (:background "red"))))
 '(custom-button-face ((((type x w32 mac) (class color)) (:background "lightgrey" :foreground "black" :box (:line-width 3 :style released-button)))))
 '(custom-comment-face ((((class grayscale color) (background dark)) (:background unspecified :foreground "pink" :slant italic))))
 '(cvs-handled-face ((nil (:foreground "green" :weight bold))))
 '(cvs-need-action-face ((nil (:foreground "orange" :weight bold))))
 '(cvs-unknown-face ((((class color) (background dark)) (:foreground "grey35" :slant italic))))
 '(diff-added-face ((t (:inherit diff-changed-face :foreground "skyblue" :weight bold))))
 '(diff-file-header-face ((t (:inherit font-lock-string-face :weight bold))))
 '(diff-header-face ((((class color) (background dark)) (:inherit font-lock-string-face))))
 '(diff-removed-face ((t (:inherit (diff-changed-face font-lock-function-name-face) :weight normal))))
 '(font-lock-builtin-face ((t (:foreground "LightCoral"))))
 '(font-lock-comment-face ((t (:italic t :foreground "pink2" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "gold"))))
 '(font-lock-doc-face ((t (:foreground "BlanchedAlmond"))))
 '(font-lock-doc-string-face ((t (:foreground "BlanchedAlmond"))))
 '(font-lock-function-name-face ((t (:bold t :foreground "goldenrod" :weight bold))))
 '(font-lock-keyword-face ((t (:bold t :foreground "DeepSkyBlue1" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "gold"))))
 '(font-lock-reference-face ((t (:foreground "LightCoral"))))
 '(font-lock-string-face ((t (:foreground "burlywood" :slant italic))))
 '(font-lock-type-face ((t (:foreground "CadetBlue1"))))
 '(font-lock-variable-name-face ((t (:foreground "SeaGreen2"))))
 '(font-lock-warning-face ((t (:foreground "yellow"))))
 '(font-lock-literal-face ((t (:foreground "SeaGreen2"))))
 '(highlight ((t (:background "gray35"))))
 '(ido-first-match-face ((t (:background "deepskyblue4" :foreground "yellow" :weight bold))))
 '(ido-only-match-face ((((class color)) (:background "deepskyblue2" :foreground "yellow2" :weight bold))))
 '(ido-subdir-face ((((class color)) (:slant italic))))
 '(isearch ((((class color) (background light)) (:background "goldenrod" :foreground "whitesmoke"))))
 '(region ((nil (:background "darkolivegreen4"))))
 '(show-paren-match-face ((t (:bold t :foreground "blue" :background "lightgreen" :weight bold))))
 '(show-paren-mismatch-face ((t (:bold t :foreground "yellow" :background "red" :weight bold)))))