(custom-set-faces
 '(default ((t (:stipple nil :background "#272822" :foreground "#F8F8F2" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height unspecified :width normal :family unspecified))))
 '(border ((t (:background "white"))))
 '(cursor ((t (:background "deeppink"))))
 '(custom-button-face ((((type x w32 mac) (class color)) (:background "black" :foreground "lightgrey" :box (:line-width 3 :style released-button)))))
 '(custom-comment-face ((((class grayscale color) (background dark)) (:background unspecified :foreground "#465457" :slant italic))))
 '(font-lock-builtin-face ((t (:foreground "LightCoral"))))
 '(font-lock-comment-face ((t (:italic t :foreground "#75715E" :slant italic))))
 '(font-lock-constant-face ((t (:bold t :foreground "#AE81FF" :weight bold))))
 '(font-lock-doc-face ((t (:foreground "#E6DB74"))))
 '(font-lock-doc-string-face ((t (:foreground "#E6DB74"))))
 '(font-lock-function-name-face ((t (:foreground "#A6E22E"))))
 '(font-lock-keyword-face ((t (:bold t :foreground "#F92672" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#A6E22E"))))
 '(font-lock-reference-face ((t (:foreground "LightCoral"))))
 '(font-lock-string-face ((t (:foreground "#E6DB74" :slant italic))))
 '(font-lock-type-face ((t (:foreground "#66D9EF"))))
 '(font-lock-variable-name-face ((t (:foreground "#FD971F"))))
 '(font-lock-warning-face ((t (:foreground "yellow"))))
 '(font-lock-literal-face ((t (:foreground "#F92672"))))
 '(highlight ((t (:background "gray25"))))
 '(ido-first-match-face ((t (:background "deepskyblue4" :foreground "yellow" :weight bold))))
 '(ido-only-match-face ((((class color)) (:background "deepskyblue2" :foreground "yellow2" :weight bold))))
 '(ido-subdir-face ((((class color)) (:slant italic))))
 '(isearch ((((class color) (background light)) (:background "goldenrod" :foreground "whitesmoke"))))
 '(region ((nil (:background "gray40"))))
 '(show-paren-match-face ((t (:bold t :foreground "cyan" :background unspecified :weight bold))))
 '(show-paren-mismatch-face ((t (:bold t :foreground "yellow" :background unspecified :weight bold)))))